### PR TITLE
Ubuntu release v57

### PR DESCRIPTION
**Pull request by souldanger**

### CODE REVIEW

**Comment by souldanger** [comment]
no success on rebasing so far...

**Comment by longsleep** [comment]
@souldanger i just rebased it and force pushed, you should copy your local branch to another name if you want to keep the commits i removed somewhere and then reset to origin/website-test - please check the built styles as there was a conflict and i took the ones from master. 

It would be good if the built styles/assets would not be part of the repository and instead be created by a build script. I could not figure out how to build them and i think there are some sass dependencies missing.

**Comment by souldanger** [comment]
@longsleep Fantastic!
the site still seems to work so please merge it.
If you have rebased from master, than yes, stuff will be missing.... like most of everything since March 14.
I have no local backup as I thought the happy GitHub people would make sure stuff wont go missing, but this only works if we don't delete ourselves...

no disrespect and nothing personal, but what are the new rules of running the repo and website? 
why didn't we like my commits / what commits are allowed / how many commits are allowed / what is allowed to be tested and what not?

**Comment by longsleep** [comment]
> @longsleep Fantastic!
> the site still seems to work so please merge it.

Well, can you just please rebuilt the styles and add another commit with them. Thanks!

> If you have rebased from master, than yes, stuff will be missing.... like most of everything since March 14.
> I have no local backup as I thought the happy GitHub people would make sure stuff wont go missing, but this only works if we don't delete ourselves...

Well technically nothing can be deleted. In any case I have made a branch of the changes before rebase. I could easily push. But you also have all your changes still in your Git repository even if they are not attached to any branch any more. So it is possible to recover them eg. by cherry picking them by commit id.

> 
> no disrespect and nothing personal, but what are the new rules of running the repo and website?
> why didn't we like my commits / what commits are allowed / how many commits are allowed / what is allowed to be tested and what not?

Well afaik no rules. I just felt that things should be cleaned up and squashed before merge to keep things as easy and clean as possible. No harm intended, but it would make reviews a lot easier if the merge requests are small and do not include lots of non-relevant or in the meanwhile already removed changes.

**Comment by souldanger** [comment]
Okeydokey!
I have updated scss/css.
Lets keep test and live clean but please give me another branch where I can test. I do not have a private personal repo and dont want to do this in public.
Also the reviewing is new to me - before Ryan or Mike just merged my pull requests.

**Comment by longsleep** [comment]
> Lets keep test and live clean but please give me another branch where I can test. I do not have a private personal repo and dont want to do this in public.

We do not need to keep test clean. It is perfectly fine for testing things - but before merging it should be cleaned up imho. Merged now :)

**Pull request merged**
